language: python
python:
- '3.5'
- '3.6'
install:
- pip install pycodestyle
- pip install mypy mypy-extensions
- pip install --upgrade .
script:
- pycodestyle --show-source fluffycow
- mypy fluffycow --ignore-missing-imports
notifications:
  email: false
